### ISSUE TITLE
CS: Système de construction

### ISSUE THREAD

**Issue by GlassAlo** [Aurea-games/Elina-s-Legacy#190]

**Comment by Valegox** [comment]
**Todo**

- [x] Migrate EBS on project
- [x] Bind EBS resources with items
- [x] Add custom info widget on hover building object
- [x] Add building object category tabs
- [ ] Bind EBS tools with items
- [ ] Create builder item that opens build menu when click with it in hand
